routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('articles', 'ArticleController');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use SoftDeletes;
    
    public $fillable = [
        'title',
        'content'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'title' => 'required',
            'content' => 'required'
        ];

        $errorMessage = [
            'required' => 'Le champ :attribute est obligatoire'
        ];

        $this->validate($request, $rules, $errorMessage);

        Article::create([
            'title' => $request->title,
            'content' => $request->content
        ]);

        return redirect(route('articles.index'))->with('success','Article saved successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id);
        return view('articles.show')->with('article', $article);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        return view('articles.edit', compact('article'));
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $article = Article::find($id);

        $rules = [
            'title' => 'required',
            'content' => 'required'
        ];

        $errorMessage = [
            'required' => 'Le champ :attribute est obligatoire'
        ];

        $this->validate($request, $rules, $errorMessage);

        $article->update([
            'title' => $request->title,
            'content' => $request->content
        ]);

        return redirect(route('articles.index'))->with('success','Article updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $article->delete();

        return redirect(route('articles.index'))->with('success','Article deleted successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Créer un article</h2>
        <div class="row">
            <form action="{{ route('articles.store') }}" method="post">
                @csrf
                @include('articles.create_fields')
            </form>

        </div>
    </div>
@endsection

resources/views/articles/create_fields.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" placeholder="Article title" value="{{ old('title') }}" class="form-control">
            @if ($errors->has('title'))
                <div class="alert alert-danger">
                    {{ $errors->first('title') }}
                </div>
            @endif
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label for="content">Content</label>
            <textarea type="text" name="content" placeholder="Article content" value="{{ old('content') }}" class="form-control"></textarea>
            @if ($errors->has('content'))
                <div class="alert alert-danger">
                    {{ $errors->first('content') }}
                </div>
            @endif
        </div>
    </div>
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Ajouter</button> &nbsp;
        <a href="{{ route('articles.index') }}" class="btn btn-danger">Retour</a>
    </div>
</div>

resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2>Créer un article</h2>
        <div class="row">
            <form action="{{ route('articles.update', $article->id) }}" method="post">
                @csrf
                <input type="hidden" name="_method" value="PATCH">
                @include('articles.edit_fields')
            </form>

        </div>
    </div>
@endsection

resources/views/articles/edit_fields.blade.php
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" placeholder="Article title" value="{{ $article->title }}" class="form-control">
            @if ($errors->has('title'))
                <div class="alert alert-danger">
                    {{ $errors->first('title') }}
                </div>
            @endif
        </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label for="content">Content</label>
            <textarea type="text" name="content" placeholder="Article content" class="form-control">{{ $article->content }}"</textarea>
            @if ($errors->has('content'))
                <div class="alert alert-danger">
                    {{ $errors->first('content') }}
                </div>
            @endif
        </div>
    </div>
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary">Modifier</button> &nbsp;
        <a href="{{ route('articles.index') }}" class="btn btn-danger">Retour</a>
    </div>
</div>

resources/views/articles/index.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h1>Liste des articles</h1>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a href="{{ route('articles.create') }}" class="btn btn-primary">Ajouter un article</a>
                        </div>
                        <div class="col-md-12">
                            @include('layouts.flash-message')
                        </div>
                        @include('articles.table')
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <div class="container">
            <div class="card">
                <div class="card-header">
                    <h1>{{ $article->title }}</h1>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            {{ $article->content }}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{ route('articles.index') }}" class="btn btn-danger">Retour</a>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/articles/table.blade.php
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Content</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
        @if ($articles->isEmpty())
            <div class="alert alert-warning">
                Aucune donnée
            </div>
        @else
            @foreach ($articles as $item)
                <tr>
                    <th scope="row"> {{ $item->id }} </th>
                    <td> {{ $item->title }} </td>
                    <td> {{ $item->content }} </td>
                    <td>
                        <a href="{{ route('articles.show', $item->id) }}" class="btn btn-primary">Show</a>
                        <a href="{{ route('articles.edit', $item->id) }}" class="btn btn-warning">Edit</a>
                        <form action="{{ route('articles.destroy', $item->id) }}" method="post">
                            @csrf
                            <input type="hidden" name="_method" value="delete">
                            <button onclick="return confirm('Confirmez-vous la suppression de cet element ?')" type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </td>
              </tr>
            @endforeach
        @endif
      
    </tbody>
</table>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}

                    <ul>
                        <li>
                            <a href="{{ route('articles.index') }}">CRUD ARTICLE</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

resources/views/layouts/flash-message.blade.php
@if ($message = Session::get('success'))
    <div class="alert alert-success alert-block">
        <button class="close" data-dismiss="alert" type="button">x</button>
        {{ $message }}
    </div>
@endif